- name: Push admin container SSH key to all LXC containers
  hosts: proxmox_rt_lxc
  gather_facts: false
  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        mode: '0700'

    - name: Push admin container public key
      ansible.builtin.authorized_key:
        user: root
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
